### ISSUE TITLE
Unclear how to deal with assets (images)

### ISSUE THREAD

**Issue by fatso83** [christianalfoni/react-app-boilerplate#8]
Where do you place images and other assets in this setup? AFAI can see, it seems I have to constantly copy the directory structures I need to both the `dist` and the `build` folder. That gets old quickly ...  Do you just add another `express.static()` folder?

**Comment by christianalfoni** [comment]
Hi @fatso83 ,

Yeah, the boilerplate i kind of minimalistic. It was intentional though as developers tend to have very different approaches to handling css, less, static stuff like images and fonts.

But as I understood your situation you are running an express server and have one folder for static assets, you have your build folder and the dist folder. So yeah, to me it makes sense to make *assets* and *build* your static folders in development and *assets* and *dist* when running in production.

Does that comply with what you are trying to achieve?

**Comment by fatso83** [comment]
that makes sense. I would perhaps make it a suggestion in the readme, though.

**Comment by christianalfoni** [comment]
Good point! Done :-)
